drug_usage = {
'Alcohols nfd'    : 	['Ingests'],
'Benzodiazepines nfd': ['Ingests'],
'Buprenorphine'   : 	['Ingests'],
#'Cannabinoids and Related Drugs nfd': ['Smokes'],
'Cannabinoids and Related Drugs, n.e.c.': ['Smokes'],
'Dexamphetamine'  : 	['Injects'],
'Diazepam'        : 	['Ingests'],

'Methamphetamine' : 	['Ingests',	'Inhales (vapour)',	'Injects',	'Not stated/inadequately described', 'Smokes',	'Sniffs (powder)'],
'Alcohol'         :   ['Ingests',	'Injects',	'Not stated/inadequately described', 'Smokes',	'Sniffs (powder)'],
'Amphetamines, n.e.c.'     : 	['Ingests',	'Inhales (vapour)',	'Injects',	'Smokes'],
'Cannabinoids'    : 	['Ingests',	'Inhales (vapour)',	'Smokes'],
'Heroin' : 	['Ingests',	'Injects', 'Smokes'],
'Methadone'       : 	['Injects', 'Ingests', 'Smokes', 'Not stated/inadequately described'],
'Other Drugs of Concern' : 	['Not stated/inadequately described', 'Sniffs (powder)'],
#'Cocaine'         : 	['Ingests','Sniffs (powder)'],
'Not Stated / Inadequately Described' : 	['Ingests',	'Not stated/inadequately described'],
'MDMA'            : 	['Ingests','Sniffs (powder)'],
'Tramadol'        : 	['Ingests'],
'Oxycodone'       : 	['Ingests'],
'Ketamine'        : 	['Ingests', 'Sniffs (powder)'],
'MDA'             : 	['Ingests'],

'ANALGESICS'      : ['Ingests'],
'Amphetamine'     : 	['Ingests',	'Inhales (vapour)',	'Injects',	'Smokes'],
'Benzodiazepines, n.e.c.': ['Ingests'],
'Caffeine'        : ['Ingests'],
'Nicotine': ['Ingests',	'Inhales (vapour)', 'Smokes'],
'Cocaine' : 	['Ingests','Sniffs (powder)', 'Injects'],
'Codeine'         : 	['Ingests'],
'Morphine': ['Ingests', 'Injects', 'Smokes','Not stated/inadequately described','Inhales (vapour)'],
'GHB type Drugs and Analogues, n.e.c.': ['Ingests', 'Inhales (vapour)'],

}